// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using expensit.MVVM.Models;

namespace expensit.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    partial class ExpenseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("expensit.MVVM.Models.ExpenseRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("payDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("expenseRecords");
                });

            modelBuilder.Entity("expensit.MVVM.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("color")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseRecordId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("expensit.MVVM.Models.Group", b =>
                {
                    b.HasOne("expensit.MVVM.Models.ExpenseRecord", null)
                        .WithMany("Groups")
                        .HasForeignKey("ExpenseRecordId");
                });

            modelBuilder.Entity("expensit.MVVM.Models.ExpenseRecord", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
